spring:
  application:
    name: fcfs

  datasource:
    url: jdbc:mariadb://localhost:3306/eventdb
    username: root
    password: qaz112
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: mongodb://localhost:27017/fcfsdb
      port: 27017


